name: Merge release branch to master

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Triggered for merging the Release branch to master'     
        required: false
        default: 'Release Preparation'
      releaseBranch:
        description: 'Branch to merge'
        required: true
      mergeBranch:
        description: 'Branch on which merge to be performed'
        required: true

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup branch and env
      run: |
        # Strip git ref prefix from version
        echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV
        echo "GPG_TTY=$(tty)" >> $GITHUB_ENV

    - name: Merging ${{ github.event.inputs.releaseBranch }} to ${{ github.event.inputs.mergeBranch }}
      run: |
           git checkout ${{ github.event.inputs.releaseBranch }}
           echo 1
           git fetch origin ${{ github.event.inputs.mergeBranch }} 
           git branch
           git checkout ${{ github.event.inputs.mergeBranch }}
           echo 2  
           git checkout ${{ github.event.inputs.releaseBranch }}
           echo 3
           git merge -s ours ${{ github.event.inputs.mergeBranch }}
           echo 4
           git checkout ${{ github.event.inputs.mergeBranch }}
           echo 5
           git merge ${{ github.event.inputs.releaseBranch }}
           echo 6

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Merging  ${{ github.event.inputs.releaseBranch }} to ${{ github.event.inputs.mergeBranch }}
        title: Merging Changes
        body: Automated PR for release preparation. This is to merge ${{ github.event.inputs.releaseBranch }} to ${{ github.event.inputs.mergeBranch }}
        branch: ${{ github.event.inputs.releaseBranch }}
        delete-branch: true
        base: ${{ github.event.inputs.mergeBranch }}
